export default {
    title: 'Mis Empresas',
    showLoading: false,
    showFormProgressBar: false,
    showModalForm: false,
    showModalReport: false,
    isUpdate:false,
    entity: {
        records: [],
        record: {},
        address: {},
        initialValues: {
            business_name: '',
            rfc: '',
            tax_regime_id: '',
            first_phone:'',
            email: '',
            address: {
                id: null,
                street: '',
                int: '',
                ext: '',
                neighbourhood: {},
                neighbourhoods: [],
                municipality: {},
                state: {},
                country: {},
                reference: '',
            },
        },
        initialValuesRFC: {
            business_name: '',
            tax_regime_id: '',
            first_phone:'',
            email: '',
            address: {
                id: null,
                street: '',
                int: '',
                ext: '',
                neighbourhood: {},
                neighbourhoods: [],
                municipality: {},
                state: {},
                country: {},
                reference: '',
            },
        },
    },
};
